// Generated by `pnpm gen:api-client` from the API's OpenAPI document (/api/v1/openapi.json).
// Do not edit by hand: change the API's Zod schemas and generate again (D30).
// Every address is relative, so requests go to the page's own origin.

/** The API's one error format (D47). */
export interface ApiErrorBody {
  error: { code: string; message: string; referenceId: string };
}

/** A refused request, with the API's code, message and reference ID. */
export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly referenceId: string | undefined;
  /** From the Retry-After header (for example the sign-in lock), in seconds. */
  readonly retryAfterSeconds: number | undefined;

  constructor(status: number, code: string, message: string, referenceId?: string, retryAfterSeconds?: number) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.code = code;
    this.referenceId = referenceId;
    this.retryAfterSeconds = retryAfterSeconds;
  }
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  let res: Response;
  try {
    res = await fetch(path, {
      method,
      credentials: 'same-origin',
      headers:
        body === undefined
          ? { accept: 'application/json' }
          : { accept: 'application/json', 'content-type': 'application/json' },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
  } catch {
    throw new ApiError(0, 'network_error', 'The server could not be reached. Check your connection and try again.');
  }
  const text = await res.text();
  let data: unknown = undefined;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = undefined;
    }
  }
  if (!res.ok) {
    const err = (data as Partial<ApiErrorBody> | undefined)?.error;
    const retryAfter = Number(res.headers.get('retry-after'));
    throw new ApiError(
      res.status,
      err?.code ?? 'error',
      err?.message ?? 'The request was refused.',
      err?.referenceId,
      Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter : undefined,
    );
  }
  return data as T;
}

/** A paged list's query parameters (D47): page, pageSize, sort and the list's filters. */
export type ListQuery = Record<string, string | number | undefined>;

/** `?a=1&b=x`, leaving out empty values; an empty string when nothing is left. */
function queryString(query?: ListQuery): string {
  if (!query) return '';
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === '') continue;
    params.set(key, String(value));
  }
  const text = params.toString();
  return text ? `?${text}` : '';
}

/** POST /api/v1/api-keys response. */
export type PostApiKeysResponse = {
  id: string;
  key: string;
};

/** GET /api/v1/api-keys response. */
export type GetApiKeysResponse = {
  items: Array<{
    id: string;
    name: string;
    role: string;
    expiresAt: string;
    revokedAt: unknown;
    createdAt: string;
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** GET /api/v1/assets response. */
export type GetAssetsResponse = {
  items: Array<{
    id: string;
    number: string;
    sourceIds: Array<string>;
    name: string;
    label: 'public' | 'internal' | 'confidential' | 'restricted';
    status: 'active' | 'retired';
    owner: string;
    version: number;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string;
    origin: 'manual' | 'import' | 'ai';
    assetType: 'server' | 'application' | 'database' | 'network_device' | 'cloud_service' | 'endpoint';
    criticality: 'low' | 'medium' | 'high' | 'critical';
    dataClassification: 'public' | 'internal' | 'confidential' | 'restricted';
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** POST /api/v1/assets response. */
export type PostAssetsResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  assetType: 'server' | 'application' | 'database' | 'network_device' | 'cloud_service' | 'endpoint';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  dataClassification: 'public' | 'internal' | 'confidential' | 'restricted';
};

/** POST /api/v1/assets request body. */
export type PostAssetsBody = {
  name: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  assetType: 'server' | 'application' | 'database' | 'network_device' | 'cloud_service' | 'endpoint';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  dataClassification: 'public' | 'internal' | 'confidential' | 'restricted';
};

/** GET /api/v1/assets/{id} response. */
export type GetAssetsIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  assetType: 'server' | 'application' | 'database' | 'network_device' | 'cloud_service' | 'endpoint';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  dataClassification: 'public' | 'internal' | 'confidential' | 'restricted';
};

/** PATCH /api/v1/assets/{id} response. */
export type PatchAssetsIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  assetType: 'server' | 'application' | 'database' | 'network_device' | 'cloud_service' | 'endpoint';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  dataClassification: 'public' | 'internal' | 'confidential' | 'restricted';
};

/** PATCH /api/v1/assets/{id} request body. */
export type PatchAssetsIdBody = {
  name?: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  assetType?: 'server' | 'application' | 'database' | 'network_device' | 'cloud_service' | 'endpoint';
  criticality?: 'low' | 'medium' | 'high' | 'critical';
  dataClassification?: 'public' | 'internal' | 'confidential' | 'restricted';
  version: number;
};

/** GET /api/v1/assets/{id}/links response. */
export type GetAssetsIdLinksResponse = {
  items: Array<{
    type: string;
    direction: 'out' | 'in';
    other: {
      id: string;
      kind: 'asset' | 'risk' | 'control' | 'policy' | 'incident';
      number: string;
      name: string;
      label: string;
      status: string;
    };
    origin: 'manual' | 'import' | 'ai';
    createdAt: string;
    createdBy: string;
  }>;
};

/** GET /api/v1/assets/{id}/map response. */
export type GetAssetsIdMapResponse = {
  nodes: Array<{
    id: string;
    number: string;
    name: string;
    assetType: string;
    criticality: string;
    label: string;
  }>;
  edges: Array<{
    type: 'HOSTS' | 'RUNS';
    fromId: string;
    toId: string;
  }>;
  truncated: boolean;
};

/** POST /api/v1/assets/{id}/retire response. */
export type PostAssetsIdRetireResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  assetType: 'server' | 'application' | 'database' | 'network_device' | 'cloud_service' | 'endpoint';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  dataClassification: 'public' | 'internal' | 'confidential' | 'restricted';
};

/** POST /api/v1/assets/{id}/retire request body. */
export type PostAssetsIdRetireBody = {
  version: number;
};

/** POST /api/v1/auth/sign-in/email response. */
export type PostAuthSignInEmailResponse =
  | {
      twoFactorRedirect: true;
    }
  | {
      token: string;
      user: {
        id: string;
        email: string;
        name: string;
        twoFactorEnabled?: boolean;
      };
    };

/** POST /api/v1/auth/sign-in/email request body. */
export type PostAuthSignInEmailBody = {
  email: string;
  password: string;
};

/** POST /api/v1/auth/sign-out response. */
export type PostAuthSignOutResponse = {
  success: boolean;
};

/** POST /api/v1/auth/sign-out request body. */
export type PostAuthSignOutBody = Record<string, never>;

/** POST /api/v1/auth/two-factor/enable response. */
export type PostAuthTwoFactorEnableResponse = {
  totpURI: string;
  backupCodes: Array<string>;
};

/** POST /api/v1/auth/two-factor/enable request body. */
export type PostAuthTwoFactorEnableBody = {
  password: string;
};

/** POST /api/v1/auth/two-factor/verify-backup-code response. */
export type PostAuthTwoFactorVerifyBackupCodeResponse = {
  token: string;
  user: {
    id: string;
    email: string;
    name: string;
    twoFactorEnabled?: boolean;
  };
};

/** POST /api/v1/auth/two-factor/verify-backup-code request body. */
export type PostAuthTwoFactorVerifyBackupCodeBody = {
  code: string;
};

/** POST /api/v1/auth/two-factor/verify-totp response. */
export type PostAuthTwoFactorVerifyTotpResponse = {
  token: string;
  user: {
    id: string;
    email: string;
    name: string;
    twoFactorEnabled?: boolean;
  };
};

/** POST /api/v1/auth/two-factor/verify-totp request body. */
export type PostAuthTwoFactorVerifyTotpBody = {
  code: string;
};

/** GET /api/v1/controls response. */
export type GetControlsResponse = {
  items: Array<{
    id: string;
    number: string;
    sourceIds: Array<string>;
    name: string;
    label: 'public' | 'internal' | 'confidential' | 'restricted';
    status: 'active' | 'retired';
    owner: string;
    version: number;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string;
    origin: 'manual' | 'import' | 'ai';
    code: string;
    framework: string;
    controlStatus: 'not_implemented' | 'planned' | 'implemented';
    lastTestedDate: string;
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** POST /api/v1/controls response. */
export type PostControlsResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  code: string;
  framework: string;
  controlStatus: 'not_implemented' | 'planned' | 'implemented';
  lastTestedDate: string;
};

/** POST /api/v1/controls request body. */
export type PostControlsBody = {
  name: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  code: string;
  framework: string;
  controlStatus: 'not_implemented' | 'planned' | 'implemented';
  lastTestedDate: string;
};

/** GET /api/v1/controls/{id} response. */
export type GetControlsIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  code: string;
  framework: string;
  controlStatus: 'not_implemented' | 'planned' | 'implemented';
  lastTestedDate: string;
};

/** PATCH /api/v1/controls/{id} response. */
export type PatchControlsIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  code: string;
  framework: string;
  controlStatus: 'not_implemented' | 'planned' | 'implemented';
  lastTestedDate: string;
};

/** PATCH /api/v1/controls/{id} request body. */
export type PatchControlsIdBody = {
  name?: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  code?: string;
  framework?: string;
  controlStatus?: 'not_implemented' | 'planned' | 'implemented';
  lastTestedDate?: string;
  version: number;
};

/** GET /api/v1/controls/{id}/links response. */
export type GetControlsIdLinksResponse = {
  items: Array<{
    type: string;
    direction: 'out' | 'in';
    other: {
      id: string;
      kind: 'asset' | 'risk' | 'control' | 'policy' | 'incident';
      number: string;
      name: string;
      label: string;
      status: string;
    };
    origin: 'manual' | 'import' | 'ai';
    createdAt: string;
    createdBy: string;
  }>;
};

/** POST /api/v1/controls/{id}/retire response. */
export type PostControlsIdRetireResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  code: string;
  framework: string;
  controlStatus: 'not_implemented' | 'planned' | 'implemented';
  lastTestedDate: string;
};

/** POST /api/v1/controls/{id}/retire request body. */
export type PostControlsIdRetireBody = {
  version: number;
};

/** GET /api/v1/health response. */
export type GetHealthResponse = {
  status: 'ok' | 'degraded';
  postgres: 'up' | 'down';
  neo4j: 'up' | 'down';
};

/** GET /api/v1/incidents response. */
export type GetIncidentsResponse = {
  items: Array<{
    id: string;
    number: string;
    sourceIds: Array<string>;
    name: string;
    label: 'public' | 'internal' | 'confidential' | 'restricted';
    status: 'active' | 'retired';
    owner: string;
    version: number;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string;
    origin: 'manual' | 'import' | 'ai';
    severity: 'low' | 'medium' | 'high' | 'critical';
    incidentStatus: 'new' | 'investigating' | 'contained' | 'resolved' | 'closed';
    occurredAt: string;
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** POST /api/v1/incidents response. */
export type PostIncidentsResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  severity: 'low' | 'medium' | 'high' | 'critical';
  incidentStatus: 'new' | 'investigating' | 'contained' | 'resolved' | 'closed';
  occurredAt: string;
};

/** POST /api/v1/incidents request body. */
export type PostIncidentsBody = {
  name: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  severity: 'low' | 'medium' | 'high' | 'critical';
  incidentStatus: 'new' | 'investigating' | 'contained' | 'resolved' | 'closed';
  occurredAt: string;
};

/** GET /api/v1/incidents/{id} response. */
export type GetIncidentsIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  severity: 'low' | 'medium' | 'high' | 'critical';
  incidentStatus: 'new' | 'investigating' | 'contained' | 'resolved' | 'closed';
  occurredAt: string;
};

/** PATCH /api/v1/incidents/{id} response. */
export type PatchIncidentsIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  severity: 'low' | 'medium' | 'high' | 'critical';
  incidentStatus: 'new' | 'investigating' | 'contained' | 'resolved' | 'closed';
  occurredAt: string;
};

/** PATCH /api/v1/incidents/{id} request body. */
export type PatchIncidentsIdBody = {
  name?: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  severity?: 'low' | 'medium' | 'high' | 'critical';
  incidentStatus?: 'new' | 'investigating' | 'contained' | 'resolved' | 'closed';
  occurredAt?: string;
  version: number;
};

/** GET /api/v1/incidents/{id}/links response. */
export type GetIncidentsIdLinksResponse = {
  items: Array<{
    type: string;
    direction: 'out' | 'in';
    other: {
      id: string;
      kind: 'asset' | 'risk' | 'control' | 'policy' | 'incident';
      number: string;
      name: string;
      label: string;
      status: string;
    };
    origin: 'manual' | 'import' | 'ai';
    createdAt: string;
    createdBy: string;
  }>;
};

/** POST /api/v1/incidents/{id}/retire response. */
export type PostIncidentsIdRetireResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  severity: 'low' | 'medium' | 'high' | 'critical';
  incidentStatus: 'new' | 'investigating' | 'contained' | 'resolved' | 'closed';
  occurredAt: string;
};

/** POST /api/v1/incidents/{id}/retire request body. */
export type PostIncidentsIdRetireBody = {
  version: number;
};

/** POST /api/v1/links response. */
export type PostLinksResponse = {
  type: string;
  fromId: string;
  toId: string;
  origin: 'manual' | 'import' | 'ai';
  createdAt: string;
  createdBy: string;
};

/** POST /api/v1/links request body. */
export type PostLinksBody = {
  type: 'HOSTS' | 'RUNS' | 'EXPOSED_TO' | 'MITIGATED_BY' | 'GOVERNED_BY' | 'IMPACTS' | 'EXPOSES';
  fromId: string;
  toId: string;
};

/** POST /api/v1/links/remove response. */
export type PostLinksRemoveResponse = {
  type: string;
  fromId: string;
  toId: string;
};

/** POST /api/v1/links/remove request body. */
export type PostLinksRemoveBody = {
  type: 'HOSTS' | 'RUNS' | 'EXPOSED_TO' | 'MITIGATED_BY' | 'GOVERNED_BY' | 'IMPACTS' | 'EXPOSES';
  fromId: string;
  toId: string;
};

/** GET /api/v1/me response. */
export type GetMeResponse = {
  user: {
    id: string;
    email: string;
    name: string;
  };
  org: {
    id: string;
    name: string;
  };
  role: string;
  clearance: string;
  mfaEnrolled: boolean;
};

/** GET /api/v1/people response. */
export type GetPeopleResponse = {
  items: Array<{
    id: string;
    name: string;
    role: string;
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** GET /api/v1/policies response. */
export type GetPoliciesResponse = {
  items: Array<{
    id: string;
    number: string;
    sourceIds: Array<string>;
    name: string;
    label: 'public' | 'internal' | 'confidential' | 'restricted';
    status: 'active' | 'retired';
    owner: string;
    version: number;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string;
    origin: 'manual' | 'import' | 'ai';
    policyVersion: string;
    effectiveDate: string;
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** POST /api/v1/policies response. */
export type PostPoliciesResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  policyVersion: string;
  effectiveDate: string;
};

/** POST /api/v1/policies request body. */
export type PostPoliciesBody = {
  name: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  policyVersion: string;
  effectiveDate: string;
};

/** GET /api/v1/policies/{id} response. */
export type GetPoliciesIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  policyVersion: string;
  effectiveDate: string;
};

/** PATCH /api/v1/policies/{id} response. */
export type PatchPoliciesIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  policyVersion: string;
  effectiveDate: string;
};

/** PATCH /api/v1/policies/{id} request body. */
export type PatchPoliciesIdBody = {
  name?: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  policyVersion?: string;
  effectiveDate?: string;
  version: number;
};

/** GET /api/v1/policies/{id}/links response. */
export type GetPoliciesIdLinksResponse = {
  items: Array<{
    type: string;
    direction: 'out' | 'in';
    other: {
      id: string;
      kind: 'asset' | 'risk' | 'control' | 'policy' | 'incident';
      number: string;
      name: string;
      label: string;
      status: string;
    };
    origin: 'manual' | 'import' | 'ai';
    createdAt: string;
    createdBy: string;
  }>;
};

/** POST /api/v1/policies/{id}/retire response. */
export type PostPoliciesIdRetireResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  policyVersion: string;
  effectiveDate: string;
};

/** POST /api/v1/policies/{id}/retire request body. */
export type PostPoliciesIdRetireBody = {
  version: number;
};

/** GET /api/v1/risks response. */
export type GetRisksResponse = {
  items: Array<{
    id: string;
    number: string;
    sourceIds: Array<string>;
    name: string;
    label: 'public' | 'internal' | 'confidential' | 'restricted';
    status: 'active' | 'retired';
    owner: string;
    version: number;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string;
    origin: 'manual' | 'import' | 'ai';
    impact: number;
    likelihood: number;
    financialExposure: number;
    rating: {
      score: number;
      band: string;
    };
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** POST /api/v1/risks response. */
export type PostRisksResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  impact: number;
  likelihood: number;
  financialExposure: number;
  rating: {
    score: number;
    band: string;
  };
};

/** POST /api/v1/risks request body. */
export type PostRisksBody = {
  name: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  impact: number;
  likelihood: number;
  financialExposure: number;
};

/** GET /api/v1/risks/{id} response. */
export type GetRisksIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  impact: number;
  likelihood: number;
  financialExposure: number;
  rating: {
    score: number;
    band: string;
  };
};

/** PATCH /api/v1/risks/{id} response. */
export type PatchRisksIdResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  impact: number;
  likelihood: number;
  financialExposure: number;
  rating: {
    score: number;
    band: string;
  };
};

/** PATCH /api/v1/risks/{id} request body. */
export type PatchRisksIdBody = {
  name?: string;
  owner?: string;
  label?: 'public' | 'internal' | 'confidential' | 'restricted';
  impact?: number;
  likelihood?: number;
  financialExposure?: number;
  version: number;
};

/** GET /api/v1/risks/{id}/links response. */
export type GetRisksIdLinksResponse = {
  items: Array<{
    type: string;
    direction: 'out' | 'in';
    other: {
      id: string;
      kind: 'asset' | 'risk' | 'control' | 'policy' | 'incident';
      number: string;
      name: string;
      label: string;
      status: string;
    };
    origin: 'manual' | 'import' | 'ai';
    createdAt: string;
    createdBy: string;
  }>;
};

/** POST /api/v1/risks/{id}/retire response. */
export type PostRisksIdRetireResponse = {
  id: string;
  number: string;
  sourceIds: Array<string>;
  name: string;
  label: 'public' | 'internal' | 'confidential' | 'restricted';
  status: 'active' | 'retired';
  owner: string;
  version: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  origin: 'manual' | 'import' | 'ai';
  impact: number;
  likelihood: number;
  financialExposure: number;
  rating: {
    score: number;
    band: string;
  };
};

/** POST /api/v1/risks/{id}/retire request body. */
export type PostRisksIdRetireBody = {
  version: number;
};

export const api = {
  /** Create a machine API key (Admin only); the key is shown only in this response */
  postApiKeys: (): Promise<PostApiKeysResponse> => request<PostApiKeysResponse>('POST', '/api/v1/api-keys'),
  /** The org's machine API keys, paged (Admin only); never the keys themselves */
  getApiKeys: (query?: ListQuery): Promise<GetApiKeysResponse> =>
    request<GetApiKeysResponse>('GET', `/api/v1/api-keys${queryString(query)}`),
  /** List assets, paged */
  getAssets: (query?: ListQuery): Promise<GetAssetsResponse> =>
    request<GetAssetsResponse>('GET', `/api/v1/assets${queryString(query)}`),
  /** Create a asset */
  postAssets: (body: PostAssetsBody): Promise<PostAssetsResponse> =>
    request<PostAssetsResponse>('POST', '/api/v1/assets', body),
  /** Open one asset */
  getAssetsId: (path: { id: string }): Promise<GetAssetsIdResponse> =>
    request<GetAssetsIdResponse>('GET', `/api/v1/assets/${encodeURIComponent(path.id)}`),
  /** Edit a asset; a stale version is refused (409 stale_version) */
  patchAssetsId: (path: { id: string }, body: PatchAssetsIdBody): Promise<PatchAssetsIdResponse> =>
    request<PatchAssetsIdResponse>('PATCH', `/api/v1/assets/${encodeURIComponent(path.id)}`, body),
  /** The asset's links whose other end the caller can see */
  getAssetsIdLinks: (path: { id: string }): Promise<GetAssetsIdLinksResponse> =>
    request<GetAssetsIdLinksResponse>('GET', `/api/v1/assets/${encodeURIComponent(path.id)}/links`),
  /** The HOSTS and RUNS map around one asset: depth 1 to 3 (default 2), at most 200 assets */
  getAssetsIdMap: (path: { id: string }): Promise<GetAssetsIdMapResponse> =>
    request<GetAssetsIdMapResponse>('GET', `/api/v1/assets/${encodeURIComponent(path.id)}/map`),
  /** Retire a asset; it is kept, never deleted */
  postAssetsIdRetire: (path: { id: string }, body: PostAssetsIdRetireBody): Promise<PostAssetsIdRetireResponse> =>
    request<PostAssetsIdRetireResponse>('POST', `/api/v1/assets/${encodeURIComponent(path.id)}/retire`, body),
  /** Sign in with email and password; with MFA set up, the second factor comes next */
  postAuthSignInEmail: (body: PostAuthSignInEmailBody): Promise<PostAuthSignInEmailResponse> =>
    request<PostAuthSignInEmailResponse>('POST', '/api/v1/auth/sign-in/email', body),
  /** End the current session */
  postAuthSignOut: (body: PostAuthSignOutBody): Promise<PostAuthSignOutResponse> =>
    request<PostAuthSignOutResponse>('POST', '/api/v1/auth/sign-out', body),
  /** Start MFA set-up: the authenticator URI and the backup codes, shown once */
  postAuthTwoFactorEnable: (body: PostAuthTwoFactorEnableBody): Promise<PostAuthTwoFactorEnableResponse> =>
    request<PostAuthTwoFactorEnableResponse>('POST', '/api/v1/auth/two-factor/enable', body),
  /** Check a backup code instead of an authenticator code */
  postAuthTwoFactorVerifyBackupCode: (
    body: PostAuthTwoFactorVerifyBackupCodeBody,
  ): Promise<PostAuthTwoFactorVerifyBackupCodeResponse> =>
    request<PostAuthTwoFactorVerifyBackupCodeResponse>('POST', '/api/v1/auth/two-factor/verify-backup-code', body),
  /** Check a 6-digit authenticator code (finishes sign-in or MFA set-up) */
  postAuthTwoFactorVerifyTotp: (body: PostAuthTwoFactorVerifyTotpBody): Promise<PostAuthTwoFactorVerifyTotpResponse> =>
    request<PostAuthTwoFactorVerifyTotpResponse>('POST', '/api/v1/auth/two-factor/verify-totp', body),
  /** List controls, paged */
  getControls: (query?: ListQuery): Promise<GetControlsResponse> =>
    request<GetControlsResponse>('GET', `/api/v1/controls${queryString(query)}`),
  /** Create a control */
  postControls: (body: PostControlsBody): Promise<PostControlsResponse> =>
    request<PostControlsResponse>('POST', '/api/v1/controls', body),
  /** Open one control */
  getControlsId: (path: { id: string }): Promise<GetControlsIdResponse> =>
    request<GetControlsIdResponse>('GET', `/api/v1/controls/${encodeURIComponent(path.id)}`),
  /** Edit a control; a stale version is refused (409 stale_version) */
  patchControlsId: (path: { id: string }, body: PatchControlsIdBody): Promise<PatchControlsIdResponse> =>
    request<PatchControlsIdResponse>('PATCH', `/api/v1/controls/${encodeURIComponent(path.id)}`, body),
  /** The control's links whose other end the caller can see */
  getControlsIdLinks: (path: { id: string }): Promise<GetControlsIdLinksResponse> =>
    request<GetControlsIdLinksResponse>('GET', `/api/v1/controls/${encodeURIComponent(path.id)}/links`),
  /** Retire a control; it is kept, never deleted */
  postControlsIdRetire: (path: { id: string }, body: PostControlsIdRetireBody): Promise<PostControlsIdRetireResponse> =>
    request<PostControlsIdRetireResponse>('POST', `/api/v1/controls/${encodeURIComponent(path.id)}/retire`, body),
  /** Whether the API can reach Postgres and Neo4j */
  getHealth: (): Promise<GetHealthResponse> => request<GetHealthResponse>('GET', '/api/v1/health'),
  /** List incidents, paged */
  getIncidents: (query?: ListQuery): Promise<GetIncidentsResponse> =>
    request<GetIncidentsResponse>('GET', `/api/v1/incidents${queryString(query)}`),
  /** Create a incident */
  postIncidents: (body: PostIncidentsBody): Promise<PostIncidentsResponse> =>
    request<PostIncidentsResponse>('POST', '/api/v1/incidents', body),
  /** Open one incident */
  getIncidentsId: (path: { id: string }): Promise<GetIncidentsIdResponse> =>
    request<GetIncidentsIdResponse>('GET', `/api/v1/incidents/${encodeURIComponent(path.id)}`),
  /** Edit a incident; a stale version is refused (409 stale_version) */
  patchIncidentsId: (path: { id: string }, body: PatchIncidentsIdBody): Promise<PatchIncidentsIdResponse> =>
    request<PatchIncidentsIdResponse>('PATCH', `/api/v1/incidents/${encodeURIComponent(path.id)}`, body),
  /** The incident's links whose other end the caller can see */
  getIncidentsIdLinks: (path: { id: string }): Promise<GetIncidentsIdLinksResponse> =>
    request<GetIncidentsIdLinksResponse>('GET', `/api/v1/incidents/${encodeURIComponent(path.id)}/links`),
  /** Retire a incident; it is kept, never deleted */
  postIncidentsIdRetire: (
    path: { id: string },
    body: PostIncidentsIdRetireBody,
  ): Promise<PostIncidentsIdRetireResponse> =>
    request<PostIncidentsIdRetireResponse>('POST', `/api/v1/incidents/${encodeURIComponent(path.id)}/retire`, body),
  /** Link two records (D200: the caller can edit either and see both) */
  postLinks: (body: PostLinksBody): Promise<PostLinksResponse> =>
    request<PostLinksResponse>('POST', '/api/v1/links', body),
  /** Remove a link added by mistake (D201: the same people who may add it). Answers 404 not_found, 403 forbidden, or 409 ai_link_review_only for a link found by the AI (D207) */
  postLinksRemove: (body: PostLinksRemoveBody): Promise<PostLinksRemoveResponse> =>
    request<PostLinksRemoveResponse>('POST', '/api/v1/links/remove', body),
  /** The signed-in user, their org, role and clearance, and whether MFA is set up */
  getMe: (): Promise<GetMeResponse> => request<GetMeResponse>('GET', '/api/v1/me'),
  /** The caller's org members for the owner picker, paged: id, name and role only */
  getPeople: (query?: ListQuery): Promise<GetPeopleResponse> =>
    request<GetPeopleResponse>('GET', `/api/v1/people${queryString(query)}`),
  /** List policies, paged */
  getPolicies: (query?: ListQuery): Promise<GetPoliciesResponse> =>
    request<GetPoliciesResponse>('GET', `/api/v1/policies${queryString(query)}`),
  /** Create a policy */
  postPolicies: (body: PostPoliciesBody): Promise<PostPoliciesResponse> =>
    request<PostPoliciesResponse>('POST', '/api/v1/policies', body),
  /** Open one policy */
  getPoliciesId: (path: { id: string }): Promise<GetPoliciesIdResponse> =>
    request<GetPoliciesIdResponse>('GET', `/api/v1/policies/${encodeURIComponent(path.id)}`),
  /** Edit a policy; a stale version is refused (409 stale_version) */
  patchPoliciesId: (path: { id: string }, body: PatchPoliciesIdBody): Promise<PatchPoliciesIdResponse> =>
    request<PatchPoliciesIdResponse>('PATCH', `/api/v1/policies/${encodeURIComponent(path.id)}`, body),
  /** The policy's links whose other end the caller can see */
  getPoliciesIdLinks: (path: { id: string }): Promise<GetPoliciesIdLinksResponse> =>
    request<GetPoliciesIdLinksResponse>('GET', `/api/v1/policies/${encodeURIComponent(path.id)}/links`),
  /** Retire a policy; it is kept, never deleted */
  postPoliciesIdRetire: (path: { id: string }, body: PostPoliciesIdRetireBody): Promise<PostPoliciesIdRetireResponse> =>
    request<PostPoliciesIdRetireResponse>('POST', `/api/v1/policies/${encodeURIComponent(path.id)}/retire`, body),
  /** List risks, paged */
  getRisks: (query?: ListQuery): Promise<GetRisksResponse> =>
    request<GetRisksResponse>('GET', `/api/v1/risks${queryString(query)}`),
  /** Create a risk */
  postRisks: (body: PostRisksBody): Promise<PostRisksResponse> =>
    request<PostRisksResponse>('POST', '/api/v1/risks', body),
  /** Open one risk */
  getRisksId: (path: { id: string }): Promise<GetRisksIdResponse> =>
    request<GetRisksIdResponse>('GET', `/api/v1/risks/${encodeURIComponent(path.id)}`),
  /** Edit a risk; a stale version is refused (409 stale_version) */
  patchRisksId: (path: { id: string }, body: PatchRisksIdBody): Promise<PatchRisksIdResponse> =>
    request<PatchRisksIdResponse>('PATCH', `/api/v1/risks/${encodeURIComponent(path.id)}`, body),
  /** The risk's links whose other end the caller can see */
  getRisksIdLinks: (path: { id: string }): Promise<GetRisksIdLinksResponse> =>
    request<GetRisksIdLinksResponse>('GET', `/api/v1/risks/${encodeURIComponent(path.id)}/links`),
  /** Retire a risk; it is kept, never deleted */
  postRisksIdRetire: (path: { id: string }, body: PostRisksIdRetireBody): Promise<PostRisksIdRetireResponse> =>
    request<PostRisksIdRetireResponse>('POST', `/api/v1/risks/${encodeURIComponent(path.id)}/retire`, body),
};
