// Generated by `pnpm gen:api-client` from the API's OpenAPI document (/api/v1/openapi.json).
// Do not edit by hand: change the API's Zod schemas and generate again (D30).
// Every address is relative, so requests go to the page's own origin.

/** The API's one error format (D47). */
export interface ApiErrorBody {
  error: { code: string; message: string; referenceId: string };
}

/** A refused request, with the API's code, message and reference ID. */
export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly referenceId: string | undefined;
  /** From the Retry-After header (for example the sign-in lock), in seconds. */
  readonly retryAfterSeconds: number | undefined;

  constructor(status: number, code: string, message: string, referenceId?: string, retryAfterSeconds?: number) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.code = code;
    this.referenceId = referenceId;
    this.retryAfterSeconds = retryAfterSeconds;
  }
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  let res: Response;
  try {
    res = await fetch(path, {
      method,
      credentials: 'same-origin',
      headers:
        body === undefined
          ? { accept: 'application/json' }
          : { accept: 'application/json', 'content-type': 'application/json' },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
  } catch {
    throw new ApiError(0, 'network_error', 'The server could not be reached. Check your connection and try again.');
  }
  const text = await res.text();
  let data: unknown = undefined;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = undefined;
    }
  }
  if (!res.ok) {
    const err = (data as Partial<ApiErrorBody> | undefined)?.error;
    const retryAfter = Number(res.headers.get('retry-after'));
    throw new ApiError(
      res.status,
      err?.code ?? 'error',
      err?.message ?? 'The request was refused.',
      err?.referenceId,
      Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter : undefined,
    );
  }
  return data as T;
}

/** POST /api/v1/auth/sign-in/email response. */
export type PostAuthSignInEmailResponse =
  | {
      twoFactorRedirect: true;
    }
  | {
      token: string;
      user: {
        id: string;
        email: string;
        name: string;
        twoFactorEnabled?: boolean;
      };
    };

/** POST /api/v1/auth/sign-in/email request body. */
export type PostAuthSignInEmailBody = {
  email: string;
  password: string;
};

/** POST /api/v1/auth/sign-out response. */
export type PostAuthSignOutResponse = {
  success: boolean;
};

/** POST /api/v1/auth/sign-out request body. */
export type PostAuthSignOutBody = Record<string, never>;

/** POST /api/v1/auth/two-factor/enable response. */
export type PostAuthTwoFactorEnableResponse = {
  totpURI: string;
  backupCodes: Array<string>;
};

/** POST /api/v1/auth/two-factor/enable request body. */
export type PostAuthTwoFactorEnableBody = {
  password: string;
};

/** POST /api/v1/auth/two-factor/verify-backup-code response. */
export type PostAuthTwoFactorVerifyBackupCodeResponse = {
  token: string;
  user: {
    id: string;
    email: string;
    name: string;
    twoFactorEnabled?: boolean;
  };
};

/** POST /api/v1/auth/two-factor/verify-backup-code request body. */
export type PostAuthTwoFactorVerifyBackupCodeBody = {
  code: string;
};

/** POST /api/v1/auth/two-factor/verify-totp response. */
export type PostAuthTwoFactorVerifyTotpResponse = {
  token: string;
  user: {
    id: string;
    email: string;
    name: string;
    twoFactorEnabled?: boolean;
  };
};

/** POST /api/v1/auth/two-factor/verify-totp request body. */
export type PostAuthTwoFactorVerifyTotpBody = {
  code: string;
};

/** GET /api/v1/health response. */
export type GetHealthResponse = {
  status: 'ok' | 'degraded';
  postgres: 'up' | 'down';
  neo4j: 'up' | 'down';
};

/** GET /api/v1/me response. */
export type GetMeResponse = {
  user: {
    id: string;
    email: string;
    name: string;
  };
  org: {
    id: string;
    name: string;
  };
  role: string;
  clearance: string;
  mfaEnrolled: boolean;
};

export const api = {
  /** Sign in with email and password; with MFA set up, the second factor comes next */
  postAuthSignInEmail: (body: PostAuthSignInEmailBody): Promise<PostAuthSignInEmailResponse> =>
    request<PostAuthSignInEmailResponse>('POST', '/api/v1/auth/sign-in/email', body),
  /** End the current session */
  postAuthSignOut: (body: PostAuthSignOutBody): Promise<PostAuthSignOutResponse> =>
    request<PostAuthSignOutResponse>('POST', '/api/v1/auth/sign-out', body),
  /** Start MFA set-up: the authenticator URI and the backup codes, shown once */
  postAuthTwoFactorEnable: (body: PostAuthTwoFactorEnableBody): Promise<PostAuthTwoFactorEnableResponse> =>
    request<PostAuthTwoFactorEnableResponse>('POST', '/api/v1/auth/two-factor/enable', body),
  /** Check a backup code instead of an authenticator code */
  postAuthTwoFactorVerifyBackupCode: (
    body: PostAuthTwoFactorVerifyBackupCodeBody,
  ): Promise<PostAuthTwoFactorVerifyBackupCodeResponse> =>
    request<PostAuthTwoFactorVerifyBackupCodeResponse>('POST', '/api/v1/auth/two-factor/verify-backup-code', body),
  /** Check a 6-digit authenticator code (finishes sign-in or MFA set-up) */
  postAuthTwoFactorVerifyTotp: (body: PostAuthTwoFactorVerifyTotpBody): Promise<PostAuthTwoFactorVerifyTotpResponse> =>
    request<PostAuthTwoFactorVerifyTotpResponse>('POST', '/api/v1/auth/two-factor/verify-totp', body),
  /** Whether the API can reach Postgres and Neo4j */
  getHealth: (): Promise<GetHealthResponse> => request<GetHealthResponse>('GET', '/api/v1/health'),
  /** The signed-in user, their org, role and clearance, and whether MFA is set up */
  getMe: (): Promise<GetMeResponse> => request<GetMeResponse>('GET', '/api/v1/me'),
};
