// The fixed demo records and links for `pnpm seed:demo` (S1-010, D114, D45.8). Plain objects, the
// same on every run. Each record's `key` becomes its source ID (`demo:<key>`), so a re-run finds it
// and adds nothing (D45.5).
// - Owners are named by the demo role; the seed turns each into that org's demo user.
// - Labels spread from `public` to `restricted`, so the demo users' mixed clearances see different
//   lists; the Control Owner owns at least 3 controls at a label their `internal` clearance sees.
// - The two orgs' data differ, so the org wall is visible.

export type DemoKind = 'asset' | 'risk' | 'control' | 'policy' | 'incident';
export type DemoLabel = 'public' | 'internal' | 'confidential' | 'restricted';
export type DemoOwner = 'admin' | 'risk_manager' | 'compliance_manager' | 'control_owner' | 'analyst';
export type DemoLinkType = 'HOSTS' | 'RUNS' | 'EXPOSED_TO' | 'MITIGATED_BY' | 'GOVERNED_BY' | 'IMPACTS' | 'EXPOSES';

export interface DemoRecord {
  key: string;
  kind: DemoKind;
  name: string;
  label: DemoLabel;
  owner: DemoOwner;
  fields: Record<string, string | number>;
}

export interface DemoLink {
  type: DemoLinkType;
  from: string;
  to: string;
}

export interface DemoData {
  records: DemoRecord[];
  links: DemoLink[];
}

/** A record's source ID: fixed, and unique in its org. */
export function demoSourceId(key: string): string {
  return `demo:${key}`;
}

const NIST = 'NIST 800-53';

const ACME: DemoData = {
  records: [
    // Assets
    {
      key: 'AST-01',
      kind: 'asset',
      name: 'Core web cluster',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'server', criticality: 'critical', dataClassification: 'confidential' },
    },
    {
      key: 'AST-02',
      kind: 'asset',
      name: 'Customer portal',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'high', dataClassification: 'confidential' },
    },
    {
      key: 'AST-03',
      kind: 'asset',
      name: 'Orders database',
      label: 'restricted',
      owner: 'admin',
      fields: { assetType: 'database', criticality: 'critical', dataClassification: 'restricted' },
    },
    {
      key: 'AST-04',
      kind: 'asset',
      name: 'Edge firewall',
      label: 'internal',
      owner: 'admin',
      fields: { assetType: 'network_device', criticality: 'high', dataClassification: 'internal' },
    },
    {
      key: 'AST-05',
      kind: 'asset',
      name: 'AWS production account',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'cloud_service', criticality: 'critical', dataClassification: 'confidential' },
    },
    {
      key: 'AST-06',
      kind: 'asset',
      name: 'Build server',
      label: 'internal',
      owner: 'admin',
      fields: { assetType: 'server', criticality: 'medium', dataClassification: 'internal' },
    },
    {
      key: 'AST-07',
      kind: 'asset',
      name: 'CI/CD pipeline',
      label: 'internal',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'medium', dataClassification: 'internal' },
    },
    {
      key: 'AST-08',
      kind: 'asset',
      name: 'HR system',
      label: 'restricted',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'high', dataClassification: 'restricted' },
    },
    {
      key: 'AST-09',
      kind: 'asset',
      name: 'Payroll database',
      label: 'restricted',
      owner: 'admin',
      fields: { assetType: 'database', criticality: 'critical', dataClassification: 'restricted' },
    },
    {
      key: 'AST-10',
      kind: 'asset',
      name: 'Office Wi-Fi controller',
      label: 'public',
      owner: 'admin',
      fields: { assetType: 'network_device', criticality: 'low', dataClassification: 'public' },
    },
    {
      key: 'AST-11',
      kind: 'asset',
      name: 'Finance laptops',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'endpoint', criticality: 'medium', dataClassification: 'confidential' },
    },
    {
      key: 'AST-12',
      kind: 'asset',
      name: 'Public marketing site',
      label: 'public',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'low', dataClassification: 'public' },
    },
    // Risks
    {
      key: 'RSK-01',
      kind: 'risk',
      name: 'Ransomware on production servers',
      label: 'confidential',
      owner: 'risk_manager',
      fields: { impact: 5, likelihood: 3, financialExposure: 2500000 },
    },
    {
      key: 'RSK-02',
      kind: 'risk',
      name: 'Customer data breach through the portal',
      label: 'restricted',
      owner: 'risk_manager',
      fields: { impact: 5, likelihood: 3, financialExposure: 4000000 },
    },
    {
      key: 'RSK-03',
      kind: 'risk',
      name: 'Unpatched firewall firmware',
      label: 'internal',
      owner: 'risk_manager',
      fields: { impact: 3, likelihood: 3, financialExposure: 250000 },
    },
    {
      key: 'RSK-04',
      kind: 'risk',
      name: 'Cloud storage left open by misconfiguration',
      label: 'confidential',
      owner: 'risk_manager',
      fields: { impact: 4, likelihood: 3, financialExposure: 1200000 },
    },
    {
      key: 'RSK-05',
      kind: 'risk',
      name: 'Phishing of staff',
      label: 'public',
      owner: 'risk_manager',
      fields: { impact: 3, likelihood: 4, financialExposure: 400000 },
    },
    {
      key: 'RSK-06',
      kind: 'risk',
      name: 'Payroll fraud by an insider',
      label: 'restricted',
      owner: 'risk_manager',
      fields: { impact: 4, likelihood: 2, financialExposure: 900000 },
    },
    {
      key: 'RSK-07',
      kind: 'risk',
      name: 'Website defacement',
      label: 'public',
      owner: 'risk_manager',
      fields: { impact: 2, likelihood: 2, financialExposure: 50000 },
    },
    {
      key: 'RSK-08',
      kind: 'risk',
      name: 'Build pipeline supply-chain compromise',
      label: 'internal',
      owner: 'risk_manager',
      fields: { impact: 4, likelihood: 2, financialExposure: 1500000 },
    },
    // Controls
    {
      key: 'CTL-01',
      kind: 'control',
      name: 'Multi-factor sign-in for remote access',
      label: 'internal',
      owner: 'control_owner',
      fields: { code: 'IA-2', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-05-12' },
    },
    {
      key: 'CTL-02',
      kind: 'control',
      name: 'Endpoint detection and response',
      label: 'internal',
      owner: 'control_owner',
      fields: { code: 'SI-4', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-04-28' },
    },
    {
      key: 'CTL-03',
      kind: 'control',
      name: 'Monthly patching',
      label: 'public',
      owner: 'control_owner',
      fields: { code: 'SI-2', framework: NIST, controlStatus: 'planned', lastTestedDate: '2026-01-20' },
    },
    {
      key: 'CTL-04',
      kind: 'control',
      name: 'Security awareness training',
      label: 'public',
      owner: 'control_owner',
      fields: { code: 'AT-2', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-03-03' },
    },
    {
      key: 'CTL-05',
      kind: 'control',
      name: 'Encrypted backups with an offline copy',
      label: 'confidential',
      owner: 'compliance_manager',
      fields: { code: 'CP-9', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-06-01' },
    },
    {
      key: 'CTL-06',
      kind: 'control',
      name: 'Web application firewall',
      label: 'confidential',
      owner: 'compliance_manager',
      fields: { code: 'SC-7', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-02-14' },
    },
    {
      key: 'CTL-07',
      kind: 'control',
      name: 'Cloud configuration monitoring',
      label: 'internal',
      owner: 'compliance_manager',
      fields: { code: 'CM-6', framework: NIST, controlStatus: 'planned', lastTestedDate: '2025-12-09' },
    },
    {
      key: 'CTL-08',
      kind: 'control',
      name: 'Quarterly privileged access reviews',
      label: 'restricted',
      owner: 'compliance_manager',
      fields: { code: 'AC-6', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-04-02' },
    },
    {
      key: 'CTL-09',
      kind: 'control',
      name: 'Dependency scanning and code signing',
      label: 'confidential',
      owner: 'compliance_manager',
      fields: { code: 'SA-11', framework: NIST, controlStatus: 'not_implemented', lastTestedDate: '2025-10-30' },
    },
    {
      key: 'CTL-10',
      kind: 'control',
      name: 'Segregation of duties in payroll',
      label: 'restricted',
      owner: 'compliance_manager',
      fields: { code: 'AC-5', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-05-20' },
    },
    // Policies
    {
      key: 'POL-01',
      kind: 'policy',
      name: 'Information Security Policy',
      label: 'public',
      owner: 'compliance_manager',
      fields: { policyVersion: '3.1', effectiveDate: '2026-01-15' },
    },
    {
      key: 'POL-02',
      kind: 'policy',
      name: 'Access Control Policy',
      label: 'internal',
      owner: 'compliance_manager',
      fields: { policyVersion: '2.0', effectiveDate: '2025-11-01' },
    },
    {
      key: 'POL-03',
      kind: 'policy',
      name: 'Backup and Recovery Policy',
      label: 'confidential',
      owner: 'compliance_manager',
      fields: { policyVersion: '1.4', effectiveDate: '2025-09-10' },
    },
    {
      key: 'POL-04',
      kind: 'policy',
      name: 'Secure Development Policy',
      label: 'internal',
      owner: 'compliance_manager',
      fields: { policyVersion: '1.0', effectiveDate: '2026-02-01' },
    },
    // Incidents
    {
      key: 'INC-01',
      kind: 'incident',
      name: 'Ransomware attempt blocked on the build server',
      label: 'confidential',
      owner: 'analyst',
      fields: { severity: 'high', incidentStatus: 'contained', occurredAt: '2026-06-03T14:20:00Z' },
    },
    {
      key: 'INC-02',
      kind: 'incident',
      name: 'Phishing email reported by finance',
      label: 'internal',
      owner: 'analyst',
      fields: { severity: 'medium', incidentStatus: 'resolved', occurredAt: '2026-05-18T09:05:00Z' },
    },
    {
      key: 'INC-03',
      kind: 'incident',
      name: 'Credential stuffing spike on the portal',
      label: 'confidential',
      owner: 'analyst',
      fields: { severity: 'high', incidentStatus: 'investigating', occurredAt: '2026-07-22T02:40:00Z' },
    },
    {
      key: 'INC-04',
      kind: 'incident',
      name: 'Payroll records opened out of hours',
      label: 'restricted',
      owner: 'analyst',
      fields: { severity: 'critical', incidentStatus: 'investigating', occurredAt: '2026-08-09T23:15:00Z' },
    },
    {
      key: 'INC-05',
      kind: 'incident',
      name: 'Marketing site defaced for 20 minutes',
      label: 'public',
      owner: 'analyst',
      fields: { severity: 'low', incidentStatus: 'closed', occurredAt: '2026-03-27T11:00:00Z' },
    },
  ],
  links: [
    { type: 'HOSTS', from: 'AST-05', to: 'AST-01' },
    { type: 'HOSTS', from: 'AST-05', to: 'AST-06' },
    { type: 'HOSTS', from: 'AST-05', to: 'AST-09' },
    { type: 'HOSTS', from: 'AST-01', to: 'AST-03' },
    { type: 'RUNS', from: 'AST-01', to: 'AST-02' },
    { type: 'RUNS', from: 'AST-01', to: 'AST-12' },
    { type: 'RUNS', from: 'AST-06', to: 'AST-07' },
    { type: 'RUNS', from: 'AST-05', to: 'AST-08' },
    { type: 'EXPOSED_TO', from: 'AST-01', to: 'RSK-01' },
    { type: 'EXPOSED_TO', from: 'AST-06', to: 'RSK-01' },
    { type: 'EXPOSED_TO', from: 'AST-02', to: 'RSK-02' },
    { type: 'EXPOSED_TO', from: 'AST-03', to: 'RSK-02' },
    { type: 'EXPOSED_TO', from: 'AST-04', to: 'RSK-03' },
    { type: 'EXPOSED_TO', from: 'AST-05', to: 'RSK-04' },
    { type: 'EXPOSED_TO', from: 'AST-11', to: 'RSK-05' },
    { type: 'EXPOSED_TO', from: 'AST-09', to: 'RSK-06' },
    { type: 'EXPOSED_TO', from: 'AST-12', to: 'RSK-07' },
    { type: 'EXPOSED_TO', from: 'AST-07', to: 'RSK-08' },
    { type: 'MITIGATED_BY', from: 'RSK-01', to: 'CTL-02' },
    { type: 'MITIGATED_BY', from: 'RSK-01', to: 'CTL-05' },
    { type: 'MITIGATED_BY', from: 'RSK-02', to: 'CTL-06' },
    { type: 'MITIGATED_BY', from: 'RSK-02', to: 'CTL-01' },
    { type: 'MITIGATED_BY', from: 'RSK-03', to: 'CTL-03' },
    { type: 'MITIGATED_BY', from: 'RSK-04', to: 'CTL-07' },
    { type: 'MITIGATED_BY', from: 'RSK-05', to: 'CTL-04' },
    { type: 'MITIGATED_BY', from: 'RSK-05', to: 'CTL-01' },
    { type: 'MITIGATED_BY', from: 'RSK-06', to: 'CTL-10' },
    { type: 'MITIGATED_BY', from: 'RSK-06', to: 'CTL-08' },
    { type: 'MITIGATED_BY', from: 'RSK-07', to: 'CTL-06' },
    { type: 'MITIGATED_BY', from: 'RSK-08', to: 'CTL-09' },
    { type: 'GOVERNED_BY', from: 'CTL-01', to: 'POL-02' },
    { type: 'GOVERNED_BY', from: 'CTL-08', to: 'POL-02' },
    { type: 'GOVERNED_BY', from: 'CTL-10', to: 'POL-02' },
    { type: 'GOVERNED_BY', from: 'CTL-02', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-03', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-04', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-07', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-05', to: 'POL-03' },
    { type: 'GOVERNED_BY', from: 'CTL-06', to: 'POL-04' },
    { type: 'GOVERNED_BY', from: 'CTL-09', to: 'POL-04' },
    { type: 'IMPACTS', from: 'INC-01', to: 'AST-06' },
    { type: 'IMPACTS', from: 'INC-02', to: 'AST-11' },
    { type: 'IMPACTS', from: 'INC-03', to: 'AST-02' },
    { type: 'IMPACTS', from: 'INC-04', to: 'AST-09' },
    { type: 'IMPACTS', from: 'INC-05', to: 'AST-12' },
    { type: 'EXPOSES', from: 'INC-01', to: 'RSK-01' },
    { type: 'EXPOSES', from: 'INC-02', to: 'RSK-05' },
    { type: 'EXPOSES', from: 'INC-03', to: 'RSK-02' },
    { type: 'EXPOSES', from: 'INC-04', to: 'RSK-06' },
    { type: 'EXPOSES', from: 'INC-05', to: 'RSK-07' },
  ],
};

const GLOBEX: DemoData = {
  records: [
    // Assets
    {
      key: 'AST-01',
      kind: 'asset',
      name: 'Fleet tracking platform',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'critical', dataClassification: 'confidential' },
    },
    {
      key: 'AST-02',
      kind: 'asset',
      name: 'Warehouse management system',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'high', dataClassification: 'confidential' },
    },
    {
      key: 'AST-03',
      kind: 'asset',
      name: 'Shipments database',
      label: 'restricted',
      owner: 'admin',
      fields: { assetType: 'database', criticality: 'critical', dataClassification: 'restricted' },
    },
    {
      key: 'AST-04',
      kind: 'asset',
      name: 'Azure tenant',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'cloud_service', criticality: 'critical', dataClassification: 'confidential' },
    },
    {
      key: 'AST-05',
      kind: 'asset',
      name: 'Depot core switch',
      label: 'internal',
      owner: 'admin',
      fields: { assetType: 'network_device', criticality: 'high', dataClassification: 'internal' },
    },
    {
      key: 'AST-06',
      kind: 'asset',
      name: 'Application server pool',
      label: 'internal',
      owner: 'admin',
      fields: { assetType: 'server', criticality: 'high', dataClassification: 'internal' },
    },
    {
      key: 'AST-07',
      kind: 'asset',
      name: 'Driver handheld scanners',
      label: 'internal',
      owner: 'admin',
      fields: { assetType: 'endpoint', criticality: 'medium', dataClassification: 'internal' },
    },
    {
      key: 'AST-08',
      kind: 'asset',
      name: 'Customer tracking page',
      label: 'public',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'low', dataClassification: 'public' },
    },
    {
      key: 'AST-09',
      kind: 'asset',
      name: 'Billing database',
      label: 'restricted',
      owner: 'admin',
      fields: { assetType: 'database', criticality: 'critical', dataClassification: 'restricted' },
    },
    {
      key: 'AST-10',
      kind: 'asset',
      name: 'Billing service',
      label: 'confidential',
      owner: 'admin',
      fields: { assetType: 'application', criticality: 'high', dataClassification: 'confidential' },
    },
    {
      key: 'AST-11',
      kind: 'asset',
      name: 'VPN gateway',
      label: 'internal',
      owner: 'admin',
      fields: { assetType: 'network_device', criticality: 'high', dataClassification: 'internal' },
    },
    {
      key: 'AST-12',
      kind: 'asset',
      name: 'Dispatch office PCs',
      label: 'public',
      owner: 'admin',
      fields: { assetType: 'endpoint', criticality: 'low', dataClassification: 'public' },
    },
    // Risks
    {
      key: 'RSK-01',
      kind: 'risk',
      name: 'GPS tracking data leak',
      label: 'confidential',
      owner: 'risk_manager',
      fields: { impact: 4, likelihood: 3, financialExposure: 800000 },
    },
    {
      key: 'RSK-02',
      kind: 'risk',
      name: 'Warehouse system outage in peak season',
      label: 'internal',
      owner: 'risk_manager',
      fields: { impact: 4, likelihood: 4, financialExposure: 1800000 },
    },
    {
      key: 'RSK-03',
      kind: 'risk',
      name: 'Billing data tampering',
      label: 'restricted',
      owner: 'risk_manager',
      fields: { impact: 5, likelihood: 2, financialExposure: 2200000 },
    },
    {
      key: 'RSK-04',
      kind: 'risk',
      name: 'Lost or stolen driver scanners',
      label: 'public',
      owner: 'risk_manager',
      fields: { impact: 2, likelihood: 4, financialExposure: 60000 },
    },
    {
      key: 'RSK-05',
      kind: 'risk',
      name: 'VPN account takeover',
      label: 'confidential',
      owner: 'risk_manager',
      fields: { impact: 4, likelihood: 3, financialExposure: 700000 },
    },
    {
      key: 'RSK-06',
      kind: 'risk',
      name: 'Ransomware in the dispatch office',
      label: 'internal',
      owner: 'risk_manager',
      fields: { impact: 4, likelihood: 3, financialExposure: 1000000 },
    },
    {
      key: 'RSK-07',
      kind: 'risk',
      name: 'Tracking page outage',
      label: 'public',
      owner: 'risk_manager',
      fields: { impact: 2, likelihood: 3, financialExposure: 30000 },
    },
    {
      key: 'RSK-08',
      kind: 'risk',
      name: 'Shipment records exposed to a partner',
      label: 'restricted',
      owner: 'risk_manager',
      fields: { impact: 5, likelihood: 2, financialExposure: 1500000 },
    },
    // Controls
    {
      key: 'CTL-01',
      kind: 'control',
      name: 'Mobile device management for scanners',
      label: 'internal',
      owner: 'control_owner',
      fields: { code: 'CM-8', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-04-11' },
    },
    {
      key: 'CTL-02',
      kind: 'control',
      name: 'Multi-factor sign-in on the VPN',
      label: 'internal',
      owner: 'control_owner',
      fields: { code: 'IA-2', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-05-06' },
    },
    {
      key: 'CTL-03',
      kind: 'control',
      name: 'Anti-malware on office PCs',
      label: 'public',
      owner: 'control_owner',
      fields: { code: 'SI-3', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-02-25' },
    },
    {
      key: 'CTL-04',
      kind: 'control',
      name: 'Change approval board',
      label: 'internal',
      owner: 'compliance_manager',
      fields: { code: 'CM-3', framework: NIST, controlStatus: 'planned', lastTestedDate: '2025-11-18' },
    },
    {
      key: 'CTL-05',
      kind: 'control',
      name: 'Database activity monitoring',
      label: 'restricted',
      owner: 'compliance_manager',
      fields: { code: 'AU-6', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-06-09' },
    },
    {
      key: 'CTL-06',
      kind: 'control',
      name: 'Warehouse failover site',
      label: 'internal',
      owner: 'compliance_manager',
      fields: { code: 'CP-7', framework: NIST, controlStatus: 'planned', lastTestedDate: '2025-12-02' },
    },
    {
      key: 'CTL-07',
      kind: 'control',
      name: 'Partner data-sharing agreements',
      label: 'confidential',
      owner: 'compliance_manager',
      fields: { code: 'SA-9', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-03-30' },
    },
    {
      key: 'CTL-08',
      kind: 'control',
      name: 'Encryption of tracking data at rest',
      label: 'confidential',
      owner: 'compliance_manager',
      fields: { code: 'SC-28', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-01-13' },
    },
    {
      key: 'CTL-09',
      kind: 'control',
      name: 'Daily billing reconciliation',
      label: 'restricted',
      owner: 'compliance_manager',
      fields: { code: 'SI-7', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-07-01' },
    },
    {
      key: 'CTL-10',
      kind: 'control',
      name: 'Uptime monitoring and alerting',
      label: 'public',
      owner: 'compliance_manager',
      fields: { code: 'SI-4', framework: NIST, controlStatus: 'implemented', lastTestedDate: '2026-05-27' },
    },
    // Policies
    {
      key: 'POL-01',
      kind: 'policy',
      name: 'Information Security Policy',
      label: 'public',
      owner: 'compliance_manager',
      fields: { policyVersion: '2.2', effectiveDate: '2025-10-01' },
    },
    {
      key: 'POL-02',
      kind: 'policy',
      name: 'Mobile Device Policy',
      label: 'internal',
      owner: 'compliance_manager',
      fields: { policyVersion: '1.3', effectiveDate: '2026-03-01' },
    },
    {
      key: 'POL-03',
      kind: 'policy',
      name: 'Business Continuity Policy',
      label: 'confidential',
      owner: 'compliance_manager',
      fields: { policyVersion: '4.0', effectiveDate: '2025-12-15' },
    },
    {
      key: 'POL-04',
      kind: 'policy',
      name: 'Third-Party Data Sharing Policy',
      label: 'restricted',
      owner: 'compliance_manager',
      fields: { policyVersion: '1.1', effectiveDate: '2026-04-20' },
    },
    // Incidents
    {
      key: 'INC-01',
      kind: 'incident',
      name: 'Scanner left in an unlocked van',
      label: 'public',
      owner: 'analyst',
      fields: { severity: 'low', incidentStatus: 'resolved', occurredAt: '2026-02-11T16:45:00Z' },
    },
    {
      key: 'INC-02',
      kind: 'incident',
      name: 'Warehouse system slowdown on Black Friday',
      label: 'internal',
      owner: 'analyst',
      fields: { severity: 'high', incidentStatus: 'closed', occurredAt: '2025-11-28T08:30:00Z' },
    },
    {
      key: 'INC-03',
      kind: 'incident',
      name: 'Suspicious VPN sign-ins from abroad',
      label: 'confidential',
      owner: 'analyst',
      fields: { severity: 'high', incidentStatus: 'investigating', occurredAt: '2026-08-14T03:10:00Z' },
    },
    {
      key: 'INC-04',
      kind: 'incident',
      name: 'Billing export sent to the wrong partner',
      label: 'restricted',
      owner: 'analyst',
      fields: { severity: 'critical', incidentStatus: 'contained', occurredAt: '2026-07-07T13:25:00Z' },
    },
    {
      key: 'INC-05',
      kind: 'incident',
      name: 'Malware found on a dispatch PC',
      label: 'internal',
      owner: 'analyst',
      fields: { severity: 'medium', incidentStatus: 'resolved', occurredAt: '2026-06-19T10:50:00Z' },
    },
  ],
  links: [
    { type: 'HOSTS', from: 'AST-04', to: 'AST-06' },
    { type: 'HOSTS', from: 'AST-04', to: 'AST-09' },
    { type: 'HOSTS', from: 'AST-04', to: 'AST-11' },
    { type: 'HOSTS', from: 'AST-06', to: 'AST-03' },
    { type: 'RUNS', from: 'AST-06', to: 'AST-01' },
    { type: 'RUNS', from: 'AST-06', to: 'AST-02' },
    { type: 'RUNS', from: 'AST-06', to: 'AST-08' },
    { type: 'RUNS', from: 'AST-06', to: 'AST-10' },
    { type: 'EXPOSED_TO', from: 'AST-01', to: 'RSK-01' },
    { type: 'EXPOSED_TO', from: 'AST-02', to: 'RSK-02' },
    { type: 'EXPOSED_TO', from: 'AST-09', to: 'RSK-03' },
    { type: 'EXPOSED_TO', from: 'AST-10', to: 'RSK-03' },
    { type: 'EXPOSED_TO', from: 'AST-07', to: 'RSK-04' },
    { type: 'EXPOSED_TO', from: 'AST-11', to: 'RSK-05' },
    { type: 'EXPOSED_TO', from: 'AST-12', to: 'RSK-06' },
    { type: 'EXPOSED_TO', from: 'AST-08', to: 'RSK-07' },
    { type: 'EXPOSED_TO', from: 'AST-03', to: 'RSK-08' },
    { type: 'MITIGATED_BY', from: 'RSK-01', to: 'CTL-08' },
    { type: 'MITIGATED_BY', from: 'RSK-02', to: 'CTL-06' },
    { type: 'MITIGATED_BY', from: 'RSK-02', to: 'CTL-10' },
    { type: 'MITIGATED_BY', from: 'RSK-03', to: 'CTL-09' },
    { type: 'MITIGATED_BY', from: 'RSK-03', to: 'CTL-05' },
    { type: 'MITIGATED_BY', from: 'RSK-04', to: 'CTL-01' },
    { type: 'MITIGATED_BY', from: 'RSK-05', to: 'CTL-02' },
    { type: 'MITIGATED_BY', from: 'RSK-06', to: 'CTL-03' },
    { type: 'MITIGATED_BY', from: 'RSK-07', to: 'CTL-10' },
    { type: 'MITIGATED_BY', from: 'RSK-08', to: 'CTL-07' },
    { type: 'MITIGATED_BY', from: 'RSK-08', to: 'CTL-05' },
    { type: 'GOVERNED_BY', from: 'CTL-01', to: 'POL-02' },
    { type: 'GOVERNED_BY', from: 'CTL-02', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-03', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-04', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-05', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-06', to: 'POL-03' },
    { type: 'GOVERNED_BY', from: 'CTL-07', to: 'POL-04' },
    { type: 'GOVERNED_BY', from: 'CTL-08', to: 'POL-01' },
    { type: 'GOVERNED_BY', from: 'CTL-09', to: 'POL-03' },
    { type: 'GOVERNED_BY', from: 'CTL-10', to: 'POL-03' },
    { type: 'IMPACTS', from: 'INC-01', to: 'AST-07' },
    { type: 'IMPACTS', from: 'INC-02', to: 'AST-02' },
    { type: 'IMPACTS', from: 'INC-03', to: 'AST-11' },
    { type: 'IMPACTS', from: 'INC-04', to: 'AST-09' },
    { type: 'IMPACTS', from: 'INC-05', to: 'AST-12' },
    { type: 'EXPOSES', from: 'INC-01', to: 'RSK-04' },
    { type: 'EXPOSES', from: 'INC-02', to: 'RSK-02' },
    { type: 'EXPOSES', from: 'INC-03', to: 'RSK-05' },
    { type: 'EXPOSES', from: 'INC-04', to: 'RSK-08' },
    { type: 'EXPOSES', from: 'INC-05', to: 'RSK-06' },
  ],
};

/** Each demo org's data, by the org's base slug. */
export const DEMO_DATA: Record<string, DemoData> = {
  'demo-acme': ACME,
  'demo-globex': GLOBEX,
};
